providers = ['python']

[phases.setup]
    nixPkgs = ['...', 'nodejs']

[phases.money-install]
    dependsOn = ['setup']
    cmds = ['npm install --prefix money']

[phases.money-build]
    dependsOn = ['money-install']
    cmds = ['npm run build --prefix money']
